# Author: Matthew Morrison
# E-mail: matt.morrison@nd.edu
#
# This is the Makefile for Lecture 3

# G++ is for the GCC compiler for C++
PP := g++

# CFLAGS are the compiler flages for when we compile C code in this course
FLAGS := -O0 -g -Wall
CXXFLAGS := -m64 -std=c++11 $(PQCFLAGS)
PQCFLAGS := -O0 -g -Wall -Wextra -Wconversion -Wshadow -pedantic -Werror -lm
PQCXX    := -m64 -std=c++11 -Weffc++ $(PQCFLAGS)



# voidTypes Example
# Command: make voidTypes
voidTypesObjs :=  voidTypes.o

voidTypes: voidTypes.o
	$(PP) $(PQCXX) -o voidTypes $(voidTypesObjs)
	./voidTypes

voidTypes.o: voidTypes.cpp
	$(PP) $(PQCXX) -c voidTypes.cpp


# voidTypes2 Example
# Command: make voidTypes2
voidTypes2Objs :=  voidTypes2.o

voidTypes2: voidTypes2.o
	$(PP) $(PQCXX) -o voidTypes2 $(voidTypes2Objs)
	./voidTypes2

voidTypes2.o: voidTypes2.cpp
	$(PP) $(PQCXX) -c voidTypes2.cpp



# voidTypes3 Example
# Command: make voidTypes3
voidTypes3Objs :=  voidTypes3.o

voidTypes3: voidTypes3.o
	$(PP) $(PQCXX) -o voidTypes3 $(voidTypes3Objs)
	./voidTypes3

voidTypes3.o: voidTypes3.cpp
	$(PP) $(PQCXX) -c voidTypes3.cpp
	
	

# voidNode Example
# Command: make voidNode
voidNodeObjs :=  voidNode.o

voidNode: voidNode.o
	$(PP) $(PQCXX) -o voidNode $(voidNodeObjs)
	./voidNode

voidNode.o: voidNode.cpp
	$(PP) $(PQCXX) -c voidNode.cpp
	
	
	
# voidNodeBad Example
# Command: make voidNodeBad
voidNodeBadObjs :=  voidNodeBad.o

voidNodeBad: voidNodeBad.o
	$(PP) $(PQCXX) -o voidNodeBad $(voidNodeBadObjs)
	./voidNodeBad

voidNodeBad.o: voidNodeBad.cpp
	$(PP) $(PQCXX) -c voidNodeBad.cpp



# voidNodeBad2 Example
# Command: make voidNodeBad2
voidNodeBad2Objs :=  voidNodeBad2.o

voidNodeBad2: voidNodeBad2.o
	$(PP) $(PQCXX) -o voidNodeBad2 $(voidNodeBad2Objs)
	./voidNodeBad2

voidNodeBad2.o: voidNodeBad2.cpp
	$(PP) $(PQCXX) -c voidNodeBad2.cpp
	


# structNode Example
# Command: make structNode
structNodeObjs :=  structNode.o

structNode: structNode.o
	$(PP) $(PQCXX) -o structNode $(structNodeObjs)
	./structNode

structNode.o: structNode.cpp
	$(PP) $(PQCXX) -c structNode.cpp


# structSimple Example
# Command: make structSimple
structSimpleObjs :=  structSimple.o

structSimple: structSimple.o
	$(PP) $(PQCXX) -o structSimple $(structSimpleObjs)
	./structSimple

structSimple.o: structSimple.cpp
	$(PP) $(PQCXX) -c structSimple.cpp


# structSimple2 Example
# Command: make structSimple2
structSimple2Objs :=  structSimple2.o

structSimple2: structSimple2.o
	$(PP) $(PQCXX) -o structSimple2 $(structSimple2Objs)
	./structSimple

structSimple2.o: structSimple2.cpp
	$(PP) $(PQCXX) -c structSimple2.cpp	

	
# structMod Example
# Command: make structMod
structModObjs :=  structMod.o

structMod: structMod.o
	$(PP) $(PQCXX) -o structMod $(structModObjs)
	./structMod

structMod.o: structMod.cpp
	$(PP) $(PQCXX) -c structMod.cpp


# classNode Example
# Command: make classNode
classNodeObjs :=  classNode.o

classNode: classNode.o
	$(PP) $(PQCXX) -o classNode $(classNodeObjs)
	./classNode

classNode.o: classNode.cpp
	$(PP) $(PQCXX) -c classNode.cpp
	
	
# classMod Example
# Command: make classMod
classModObjs :=  classMod.o

classMod: classMod.o
	$(PP) $(PQCXX) -o classMod $(classModObjs)
	./classMod

classMod.o: classMod.cpp
	$(PP) $(PQCXX) -c classMod.cpp
	
	
# classBad Example
# Command: make classBad
classBadObjs :=  classBad.o

classBad: classBad.o
	$(PP) $(PQCXX) -o classBad $(classBadObjs)
	./classBad

classBad.o: classBad.cpp
	$(PP) $(PQCXX) -c classBad.cpp
	
	
	
# classBadPQC Example
# Command: make classBadPQC
classBadPQCObjs :=  classBadPQC.o

classBadPQC: classBadPQC.o
	$(PP) $(PQCXX) -o classBadPQC $(classBadPQCObjs)
	./classBadPQC

classBadPQC.o: classBad.cpp
	$(PP) $(PQCXX) -c classBad.cpp
	
	
# const Example
# Command: make const
constObjs :=  const.o

const: const.o
	$(PP) $(PQCXX) -o const $(constObjs)
	./const

const.o: const.cpp
	$(PP) $(PQCXX) -c const.cpp



# funcOver Example
# Command: make funcOver
funcOverObjs :=  funcOver.o

funcOver: funcOver.o
	$(PP) $(PQCXX) -o funcOver $(funcOverObjs)
	./funcOver

funcOver.o: funcOver.cpp
	$(PP) $(PQCXX) -c funcOver.cpp
	
	
# ambiguous Example
# Command: make ambig
ambigObjs :=  ambig.o

ambig: ambig.o
	$(PP) $(PQCXX) -o ambig $(ambigObjs)
	./ambig

ambig.o: ambig.cpp
	$(PP) $(PQCXX) -c ambig.cpp



# template Example
# Command: make template
templateObjs :=  template.o

template: template.o
	$(PP) $(PQCXX) -o template $(templateObjs)
	./template

template.o: template.cpp
	$(PP) $(PQCXX) -c template.cpp	

# Make all
all: voidTypes voidTypes2 voidTypes3 voidNode voidNodeBad voidNodeBad2 structNode structSimple structMod classNode classMod classBad const ambig template

# Make clean
clean :
	rm -rf *.o voidTypes voidTypes2 voidTypes3 voidNode voidNodeBad voidNodeBad2 structNode structSimple structMod classNode classMod classBad const ambig template
